# Generated by Django 5.0 on 2023-12-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataperson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("register", models.CharField(max_length=100)),
                ("member", models.CharField(max_length=100)),
                ("type_rice", models.CharField(max_length=100)),
                ("data", models.DateField(auto_now_add=True)),
                ("image", models.FileField(upload_to="")),
            ],
        ),
    ]
