# Generated by Django 5.0 on 2024-01-23 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_remove_dataperson_data_data_size_date_size_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataperson",
            old_name="date",
            new_name="data",
        ),
    ]
