# Generated by Django 5.0 on 2024-01-23 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_rename_date_dataperson_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataperson",
            name="data",
        ),
        migrations.AddField(
            model_name="dataperson",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="data_size",
            name="date_size",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="data_type",
            name="date_type",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
