# Generated by Django 5.0 on 2024-03-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0024_data_type_resultall_percent_d"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataperson",
            name="username",
            field=models.CharField(default="SOME STRING", max_length=50, unique=True),
        ),
    ]
