# Generated by Django 5.0 on 2024-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_datauser"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataperson",
            name="user_name",
            field=models.CharField(default="Guest", max_length=100),
        ),
    ]
