# Generated by Django 5.0 on 2024-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_dataperson_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data_size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultall_G", models.CharField(max_length=100)),
                ("resultall_B", models.CharField(max_length=100)),
                ("totalall", models.CharField(max_length=100)),
                ("resultall_b1", models.CharField(max_length=100)),
                ("resultall_b2", models.CharField(max_length=100)),
                ("resultall_b3", models.CharField(max_length=100)),
                ("average_h", models.CharField(max_length=100)),
                ("average_w", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Data_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultall_percent_G", models.CharField(max_length=100)),
                ("resultall_percent_C", models.CharField(max_length=100)),
                ("resultall_percent_B", models.CharField(max_length=100)),
                ("resultall_percent_Y", models.CharField(max_length=100)),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="static/images"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="static/images"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="static/images"),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, null=True, upload_to="static/images"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="dataperson",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
    ]
