# Generated by Django 5.0 on 2024-01-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_remove_data_size_time_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data_size",
            name="date_size",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="data_type",
            name="date_type",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dataperson",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
