# Generated by Django 5.0 on 2024-02-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0022_alter_data_size_date_size_alter_data_type_date_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="data_type",
            name="image5",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
    ]
