# Generated by Django 5.0 on 2024-02-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0023_data_type_image5"),
    ]

    operations = [
        migrations.AddField(
            model_name="data_type",
            name="resultall_percent_D",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
    ]
