# Generated by Django 5.0 on 2024-03-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0025_dataperson_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataperson",
            name="username",
            field=models.CharField(default="Null", max_length=50),
        ),
    ]
